[custom.dataset]
annotation_path = "/jan/dataset/pai_garden/ground_truth_llava.json"
media_path = "/jan/dataset/pai_garden"
system_prompt = "You are a helpful assistant that can answer questions about a street-view CCTV footage."

[custom.vision]
fps = 1
max_pixels = 81920

[train]
output_dir = "outputs/llava_sft"
optm_warmup_steps = 0
train_batch_per_replica = 4
compile=false
# enable_validation = false

[policy]
model_name_or_path = "nvidia/Cosmos-Reason2-2B"
model_max_length = 32768

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_reason2_object_detection"
experiment_name = "cosmos_rl/llava_sft"

[train.train_policy]
type = "sft"
mini_batch = 1
dataset.test_size = 0

[train.ckpt]
enable_checkpoint = true

[policy.parallelism]
tp_size = 1
cp_size = 1
dp_shard_size = 1
pp_size = 1